<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBtGHTS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBtGHTS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXBtGHTS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXBtGHTS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXBtGHTS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XBtGHTS',
    'container.build_id' => 'bc1f8bdc',
    'container.build_time' => 1652184698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBtGHTS');
